### ISSUE TITLE
error deploying on clients (0.5.3 on puppet 3.2.3)

### ISSUE THREAD

**Issue by mykaul** [thias/puppet-puppet#2]
/Stage[main]/Puppet::Common/Exec[catpuppetconf]	/bin/cat /etc/puppet/puppetagent.conf /etc/puppet/puppetmaster.conf > /etc/puppet/puppet.conf returned 1 instead of one of [0]

The reason is that /etc/puppet/puppetmaster.conf does NOT exist on my clients.

**Comment by thias** [comment]
This report is very old, and I honestly still have no idea why this could have been happening, so closing.
